FROM python:3.12-slim
WORKDIR /app
COPY backend/req.txt ./
RUN pip install --no-cache-dir -r req.txt
COPY backend/ ./
ENV PYTHONUNBUFFERED=1
RUN python manage.py migrate --noinput
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
